services:

  docker-sync:
    image: brianwolf94/docker-sync:latest
    container_name: docker-sync
    hostname: docker-sync
    restart: always
    environment:
      GIT_USER: brianwolf
      GIT_TOKEN: ${GIT_TOKEN}
      GIT_REPO_NAME: dockers-cluster
      GIT_BRANCH: main
      GIT_CLONE_PATH: /tmp/repo
      TIME_SECONDS_CHECK: 300
    networks:
      - docker-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  docker-net:
    name: docker-net
